package com.androidapp.mcs.tvseriesguide.database;

import android.arch.persistence.room.Dao;
import android.arch.persistence.room.Insert;
import android.arch.persistence.room.Query;

import com.androidapp.mcs.tvseriesguide.model.Series;

import java.util.List;

@Dao
public interface SeriesDao {                                                         //Implementation of this interface will be generated by ROOM
                                                                                    //This is where queries are defined
    @Insert                                                                         //Insert annotation is interpreted by the room library and SQL code is generated automatically in the background
    void insertAllSeries(List<Series> series);


    @Query("SELECT COUNT(*) from series")
    int countItems();


    @Query("SELECT * FROM Series")                                                   //Select all data from Series Table
    List<Series> getAllSeries();                                                    //The execution and return of the data is handled by room


//
//    @Insert
//    void insertAllEpisodes(List<Episode> episodes);
//
//    @Insert
//    void insertAllDetails(List<Details> detailsList);


}
